# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45bde3dcb132415701178d5fe3c13271a991a339708e1c7fe3a836994d339fc93981ef85735d7222d1b99d99c73fe83356d2a7062014dca7a293aeb1dfa28a09

test:
  secret_key_base: a4fb6dcd77f73a48b3fb7276d899bcaa7e8c159e51c981ce071c4cf845a3b409dd6626767fc0045a7ace92a7e25b6feb6627f4f7e652cb9b0769874326425514

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
